sudo: false

language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - nightly

before_install:
install:
before_script:
script:
after_success:
after_failure:
after_script:
before_deploy:
deploy:
after_deploy:
