sudo: false

env:

language: php

php:
  - 5.6
  - 7.0
  - nightly

before_install:

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - echo $HOME


before_script:
  - phpenv config-add php.ini.dist

script:
  - ./vendor/php-cs-fixer fix

after_success:
after_failure:
after_script:
before_deploy:
deploy:
after_deploy:
